#!/bin/zsh

# Autload every function in my .zsh/func/ directory
for file in ~/.zsh/func/*[^~] ; do
    autoload -U ${file##*/}
done

autoload -U zargs

# Define a function to open manpages in preview (and maintain man's completion)
pman () {
    man -t "$@" | open -f -a Preview
}
compdef _man pman

take() {
    mkdir -p $1
    cd $1
}

function copyfile {
    [[ "$#" != 1 ]] && return 1
    local file_to_copy=$1
    cat $file_to_copy | pbcopy
}


function copydir {
    pwd | tr -d "\r\n" | pbcopy
  }
